######################################################################
# Automatically generated by qmake (3.0) ?? 9? 22 00:12:13 2018
######################################################################

TEMPLATE = app
TARGET = rosaria
INCLUDEPATH += .

# Input
HEADERS += ArTimeToROSTime.h LaserPublisher.h
SOURCES += LaserPublisher.cpp RosAria.cpp
